@echo on

TITLE Copy files and paste onto new folder 
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ADAL.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ADAL.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ADITHYA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ADITHYA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ADRIELLE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ADRIELLE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\AIDY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\AIDY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\AILEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\AILEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ALAYNE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ALAYNE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ALESSIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ALESSIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ALEXANE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ALEXANE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ALIANDRA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ALIANDRA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\AMES.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\AMES.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ANALISE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ANALISE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ANNALISE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ANNALISE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ANNLIE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ANNLIE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ARNELL.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ARNELL.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ARRIANA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ARRIANA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ARVEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ARVEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ASTRID.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ASTRID.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ATHEA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ATHEA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\AUBRYN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\AUBRYN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\AYLIVIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\AYLIVIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\bahiti.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\bahiti.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BARYA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BARYA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BARYL.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BARYL.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BEARLY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BEARLY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BEATRIX.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BEATRIX.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BECKLYN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BECKLYN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BECKLYNN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BECKLYNN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BELLARY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BELLARY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BERRIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BERRIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BERRYL.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BERRYL.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BETTYY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BETTYY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BEXLEY (2).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BEXLEY (2).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BEXLEY (3).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BEXLEY (3).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BEXLEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BEXLEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BILLYNE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BILLYNE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BINDY-P.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BINDY-P.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BLUME_2.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BLUME_2.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BRIAHNA(2).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BRIAHNA(2).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BRICKLEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BRICKLEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BRIENNE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BRIENNE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BRIGITTE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BRIGITTE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\BRILYNN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\BRILYNN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CAILEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CAILEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CAITIE (2).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CAITIE (2).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CAITIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CAITIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CAITLAN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CAITLAN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CALYNN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CALYNN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CAMECO.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CAMECO.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CARIEN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CARIEN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CARLINA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CARLINA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CASHA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CASHA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CATIE (2).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CATIE (2).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CATIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CATIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CEELEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CEELEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CHERILYN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CHERILYN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CLARIBEL.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CLARIBEL.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\COLEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\COLEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CORISSA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CORISSA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CORRYN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CORRYN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CRAZE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CRAZE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\CYDNEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\CYDNEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DAISYY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DAISYY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DANEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DANEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DANI.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DANI.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DANLEA_N.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DANLEA_N.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DANLEA-N.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DANLEA-N.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DANNIKA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DANNIKA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DARLYNN.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DARLYNN.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DARVINE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DARVINE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DEANICA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DEANICA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DELAYNE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DELAYNE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DELINDA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DELINDA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DENYA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DENYA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DEVINA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DEVINA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\devon.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\devon.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DEXLEE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DEXLEE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\DYANNA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\DYANNA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\EISHA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\EISHA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ELAYNA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ELAYNA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ELERI.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ELERI.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ELICIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ELICIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\EMERSYN.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\EMERSYN.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\EMMALEE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\EMMALEE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ETHELL.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ETHELL.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ETIENNE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ETIENNE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\EVARY.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\EVARY.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\FARELLA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\FARELLA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\FELISA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\FELISA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\FIYERA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\FIYERA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\FLORBELA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\FLORBELA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\FLORENS.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\FLORENS.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\FRANLEY.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\FRANLEY.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\FRANYA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\FRANYA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\FRANZISKA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\FRANZISKA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\FYNNLEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\FYNNLEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\GARCELLE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\GARCELLE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\GARLANA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\GARLANA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\GARNIE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\GARNIE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Garren – ZG14268C-27.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\Garren – ZG14268C-27.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\GENEVRA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\GENEVRA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\GEORGIE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\GEORGIE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Gillee (2).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\Gillee (2).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Gillee (3).JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\Gillee (3).JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Gillee (4).JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\Gillee (4).JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Gillee (5).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\Gillee (5).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Gillee (6).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\Gillee (6).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Gillee.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\Gillee.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\GIUSTINA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\GIUSTINA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\GLENNA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\GLENNA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\GRADIE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\GRADIE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\GRAYCEE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\GRAYCEE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HANOVER.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HANOVER.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HARLAN.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HARLAN.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HARLETH.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HARLETH.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HASH.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HASH.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HAVON.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HAVON.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HAZELINE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HAZELINE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HELYN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HELYN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HEMMA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HEMMA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HENDALL.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HENDALL.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HIGHSCRIPT E (2).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HIGHSCRIPT E (2).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HOLLEY (2).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HOLLEY (2).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HOLLEY (3).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HOLLEY (3).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HOLLEY (4).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HOLLEY (4).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HOLLEY (5).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HOLLEY (5).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HOLLEY (6).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HOLLEY (6).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HOLLEY (7).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HOLLEY (7).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HOLLEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HOLLEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HOLLIN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HOLLIN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\HURLEY.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\HURLEY.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\INDERA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\INDERA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\IOLETTA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\IOLETTA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\IRVINE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\IRVINE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\IZABELLE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\IZABELLE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\JACKLEEN.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\JACKLEEN.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\JADELYN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\JADELYN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\JAINA (6).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\JAINA (6).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\JAINA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\JAINA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\JANNEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\JANNEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\JAYLEEN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\JAYLEEN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\JERRIE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\JERRIE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\JOURDAIN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\JOURDAIN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\KAITRIN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\KAITRIN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\KARINE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\KARINE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\KARTIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\KARTIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\KAYCIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\KAYCIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\KAYDANCE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\KAYDANCE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\KAYNE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\KAYNE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\KEALIE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\KEALIE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\KEARNEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\KEARNEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\KELLETH.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\KELLETH.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\KENSIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\KENSIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\KERLYNN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\KERLYNN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\KEYLIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\KEYLIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LADD.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LADD.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LADD-S.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LADD-S.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LANAYA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LANAYA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LANDY.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LANDY.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LARLYN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LARLYN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LARZA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LARZA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LAURENA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LAURENA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LEALEA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LEALEA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LEIANA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LEIANA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LENYA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LENYA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LEYAN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LEYAN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LEYLAN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LEYLAN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LEYNA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LEYNA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LEYRA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LEYRA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LIELLE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LIELLE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LILYBELL.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LILYBELL.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LINDYN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LINDYN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LIPTON-W.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LIPTON-W.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LOCHLAN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LOCHLAN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LOTTE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LOTTE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\LYNZEE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\LYNZEE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MABEL.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MABEL.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MAKAILYN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MAKAILYN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MARAY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MARAY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MARDIE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MARDIE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MARINI.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MARINI.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MARJIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MARJIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MARVINE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MARVINE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MERRIE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MERRIE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MIAMI.jpeg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MIAMI.jpeg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MIKAELA (2).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MIKAELA (2).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MIKAELA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MIKAELA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MILANIA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MILANIA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MYLANA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MYLANA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\MYRIAM.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\MYRIAM.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NADILEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NADILEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NAVON.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NAVON.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NAYANA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NAYANA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NAYOMIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NAYOMIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NEELIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NEELIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NEVIANA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NEVIANA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NIANA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NIANA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NICA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NICA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NICCI (2).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NICCI (2).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NICCI (3).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NICCI (3).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NICCI (4).jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NICCI (4).jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NICCI.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NICCI.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NICHOLE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NICHOLE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NIKOLA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NIKOLA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NIKOLETA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NIKOLETA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NIXIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NIXIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\NYDELLE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\NYDELLE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\OAKLEN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\OAKLEN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ODELLA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ODELLA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\OFEIBEA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\OFEIBEA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\OLIRELLA.jpeg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\OLIRELLA.jpeg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ONLEA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ONLEA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ONLEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ONLEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ORIELLE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ORIELLE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ORINDA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ORINDA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ORLEAN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ORLEAN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\OTTAVIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\OTTAVIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\OXANA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\OXANA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\PAIGELY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\PAIGELY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\PAXLEY.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\PAXLEY.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\PENINA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\PENINA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\PHEBE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\PHEBE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\PHENIX.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\PHENIX.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\PREM ZIGI.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\PREM ZIGI.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\PRESLEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\PRESLEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\PRIYANKA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\PRIYANKA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\RAINIA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\RAINIA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\RAIVYN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\RAIVYN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\READE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\READE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\REILAN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\REILAN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\RENATTA.jpeg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\RENATTA.jpeg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\RICKELLE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\RICKELLE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\RIELLE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\RIELLE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\RIPLEY- GREY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\RIPLEY- GREY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\RIPLEY-BEIGE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\RIPLEY-BEIGE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\RIPLEY-BLACK.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\RIPLEY-BLACK.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\RIPLEY-S-BLACK.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\RIPLEY-S-BLACK.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\RIPLEY-S-YELLOW.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\RIPLEY-S-YELLOW.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ROSALINE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ROSALINE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ROSALINE.png" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ROSALINE.png"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ROSELLE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ROSELLE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SABRIYA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SABRIYA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SADIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SADIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SANDYE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SANDYE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SANYA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SANYA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SAPHIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SAPHIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SARAY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SARAY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SARILA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SARILA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SARON.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SARON.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SAVITA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SAVITA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SAYDEE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SAYDEE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SAYSANA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SAYSANA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SELEEN.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SELEEN.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SELIE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SELIE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SEREIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SEREIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SESILIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SESILIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SHANNYN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SHANNYN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SHARRIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SHARRIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SHAYLIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SHAYLIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SHER.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SHER.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SHERRON.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SHERRON.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Silky (1) - Copy.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\Silky (1) - Copy.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Silky (1).JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\Silky (1).JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SINDY.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SINDY.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SIYAH.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SIYAH.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SKYLAH.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SKYLAH.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SONNI.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SONNI.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\STEPHANY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\STEPHANY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\STEVIE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\STEVIE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\STRAPPED IN BLACK.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\STRAPPED IN BLACK.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\SYNTHIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\SYNTHIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TAKOMA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TAKOMA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TAMARIS.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TAMARIS.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TARON.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TARON.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TARRAN.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TARRAN.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TARRIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TARRIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TASZIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TASZIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TAWNIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TAWNIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TEENA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TEENA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TEILA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TEILA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TEISHA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TEISHA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TELLINE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TELLINE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TEREZA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TEREZA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TERRELL.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TERRELL.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TERRINE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TERRINE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TESSALY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TESSALY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\THALIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\THALIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TIAHNA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TIAHNA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TINLEY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TINLEY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TORRIE.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TORRIE.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TREANNA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TREANNA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TRIANA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TRIANA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TRICE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TRICE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TRISTINE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TRISTINE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TRYIANA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TRYIANA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TRYSTA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TRYSTA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TURLIE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TURLIE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TUTTLE.jpeg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TUTTLE.jpeg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\TWILA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\TWILA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Valere (1).JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\Valere (1).JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\VARINA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\VARINA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\VARSHA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\VARSHA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\VELLYN.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\VELLYN.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\VERINA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\VERINA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\WANDELL.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\WANDELL.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\WANDY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\WANDY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\WANDY.png" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\WANDY.png"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\WEISZ.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\WEISZ.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\WINDSOR.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\WINDSOR.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\YASMINE.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\YASMINE.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\YASMINE.png" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\YASMINE.png"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\YELITA.JPG" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\YELITA.JPG"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\YESSICA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\YESSICA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\YLIANA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\YLIANA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\YNEZ.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\YNEZ.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\YOLANDA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\YOLANDA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\YOLARA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\YOLARA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\YULIA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\YULIA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\YULIA.png" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\YULIA.png"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ZABRYNA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ZABRYNA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ZARAY.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ZARAY.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ZEVA.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ZEVA.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ZIYAH.jpg" "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ZIYAH.jpg"
xCopy "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\ZOEVA.JPG "C:\Users\Eric\Desktop\SHOES\StyleCostFix\All Photos\Juniors\ZOEVA.JPG

pause